version: "3"
services:
  nats:
    image: nats
    expose:
      - '4222'
    ports:
      - '8222:8222'
    networks:
      - messaging-network
  sum:
    build: .
    links:
      - nats
    environment:
      NATS_URI: nats://nats:4222
    depends_on:
      - nats
    networks:
      - nats-net
networks:
  messaging-network:
    driver: bridge